from __future__ import annotations

import os
from pathlib import Path

# Central runtime settings for the local GAS server implementation. Agent developers
# usually do not edit this file when adding a new service; new services are
# discovered from service wrappers and capability JSON files.

# Flask bind settings used by `python -m gas_server.entrypoints.gas_server`.
SERVER_HOST = "0.0.0.0"
SERVER_PORT = 4042

# PROJECT_ROOT is the repository root. Data and Output live outside the package
# so generated files do not mix with source code.
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "Data"
OUTPUT_DIR = PROJECT_ROOT / "Output"

# Internal stream-event debug logging is useful while developing a new agent,
# but should not be exposed by default in public deployments.
ENABLE_STREAM_DEBUG = os.getenv("GAS_ENABLE_STREAM_DEBUG", "").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}


def agent_data_folders() -> tuple[str, ...]:
    """Return agent data folder names based on DescribeAgent JSON files.

    This keeps per-agent runtime folders automatic. Adding
    `gas_server/capabilities/my_agent.json` creates `Data/my_agent` the next
    time runtime directories are ensured.
    """
    capability_dir = PROJECT_ROOT / "gas_server" / "capabilities"
    return tuple(
        sorted(
            path.stem
            for path in capability_dir.glob("*_agent.json")
            if path.is_file()
        )
    )


def ensure_runtime_dirs() -> None:
    """Create shared and per-agent runtime output folders."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    for agent_folder in agent_data_folders():
        (DATA_DIR / agent_folder).mkdir(parents=True, exist_ok=True)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def as_str(path: Path) -> str:
    """Small helper for older code that expects string paths."""
    return str(path)
