from __future__ import annotations

import base64
import csv
from datetime import datetime, timezone, timedelta
from http import HTTPStatus
import json
import mimetypes
import os
from pathlib import Path
import random
import re
import requests
import shutil
import string
import threading
from urllib.parse import urlparse
import uuid
from typing import Any, Dict, List, Tuple

from flask import Flask, Response, has_request_context, jsonify, request, send_from_directory

from gas_server.core.artifact_inspection import inspect_artifact
from gas_server.core.config import DATA_DIR, ENABLE_STREAM_DEBUG, ensure_runtime_dirs
from gas_server.core.llm_client import configure_agent_client
from gas_server.core.specs import AgentSpec


# Shared Flask/GAS service machinery for every published GAS agent.
#
# Agent developers usually do not edit this file when adding a new service.
# The normal plugin (agent) path is:
#   1. implement a GeoAgent subclass in gas_server/agents
#   2. publish it with a tiny wrapper in gas_server/services
#   3. describe it with a capability JSON file in gas_server/capabilities
#
# This module handles the common HTTP routes, request parsing, dataset
# materialization, streaming events, async task storage, artifact delivery, and
# standard task-response normalization for all registered agents.
TERMINAL_STATES = {
    "TASK_STATE_COMPLETED",
    "TASK_STATE_FAILED",
    "TASK_STATE_CANCELED",
    "TASK_STATE_REJECTED",
}

STATE_TO_STATUS = {
    "TASK_STATE_SUBMITTED": "accepted",
    "TASK_STATE_WORKING": "running",
    "TASK_STATE_COMPLETED": "successful",
    "TASK_STATE_FAILED": "failed",
    "TASK_STATE_CANCELED": "canceled",
    "TASK_STATE_REJECTED": "failed",
}

TERMINAL_STATUSES = {"successful", "failed", "canceled", "rejected"}

STREAMING_AGENT_IDS = set(SPECS.keys()) if "SPECS" in globals() else set()
STREAM_DEBUG_LOGS: List[Dict[str, Any]] = []
STREAM_DEBUG_MAX_EVENTS = 1000

REQUEST_OPENAI_KEY_FIELDS = (
    "OPENAI API KEY",
    "OPENAI_API_KEY",
    "openai_api_key",
    "openaiApiKey",
)

REQUEST_GIBD_KEY_FIELDS = (
    "GIBD API KEY",
    "GIBD_API_KEY",
    "gibd_api_key",
    "gibdApiKey",
)


def _has_model_credentials(credentials: Dict[str, str | None]) -> bool:
    return bool(credentials.get("openai_api_key") or credentials.get("gibd_api_key"))


def _requires_model_credentials(spec: AgentSpec) -> bool:
    return bool(getattr(spec, "requires_model_credentials", True))


def _configure_agent_client_if_available(
    agent: Any,
    *,
    agent_name: str,
    credentials: Dict[str, str | None],
) -> None:
    if not _has_model_credentials(credentials):
        return
    configure_agent_client(
        agent,
        service_name=agent_name,
        openai_api_key=credentials["openai_api_key"],
        gibd_api_key=credentials["gibd_api_key"],
    )

REQUEST_OUTPUT_DELIVERY_FIELDS = (
    "output_delivery",
    "outputDelivery",
)

REQUEST_STREAM_FIELDS = (
    "stream",
    "Stream",
    "STREAM",
)

DATASET_PATH_KEYS = {
    "dataset_path",
    "dataset_paths",
    "input_dataset_path",
    "output_dataset_path",
}

INPUT_DATASETS_FIELD = "input_datasets"

PROJECT_ROOT = Path(__file__).resolve().parents[2]
JSON_DIR = PROJECT_ROOT / "gas_server" / "capabilities"
DEFAULT_PUBLIC_BASE_URL = "https://www.geospatial-agentic-services.online"


def _iso_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _record_stream_debug(event: str, **data: Any) -> None:
    if not ENABLE_STREAM_DEBUG:
        return
    try:
        STREAM_DEBUG_LOGS.append(
            {
                "timestamp": _iso_now(),
                "event": event,
                **data,
            }
        )
        if len(STREAM_DEBUG_LOGS) > STREAM_DEBUG_MAX_EVENTS:
            del STREAM_DEBUG_LOGS[: len(STREAM_DEBUG_LOGS) - STREAM_DEBUG_MAX_EVENTS]
    except Exception:
        pass


def _json_response(payload: Dict[str, Any], status_code: int, version: str | None = None) -> Response:
    response = Response(
        json.dumps(payload, indent=2),
        status=status_code,
        mimetype="application/json",
    )
    return response


def _gas_error(
    code: str,
    message: str,
    *,
    status_code: int,
    version: str | None = None,
    data: Dict[str, Any] | None = None,
) -> Response:
    payload = {"error": {"code": code, "message": message}}
    if data is not None:
        payload["error"]["data"] = data
    return _json_response(payload, status_code, version)


def _normalize_input_dataset_strings(values: Any) -> List[str]:
    if values is None:
        return []
    if isinstance(values, str):
        values = [values]

    normalized: List[str] = []
    for value in values:
        if isinstance(value, str) and "\n" in value:
            normalized.extend(part.strip() for part in value.split("\n") if part.strip())
        elif value:
            normalized.append(str(value))
    return normalized


def _uploads_root() -> Path:
    ensure_runtime_dirs()
    root = DATA_DIR / "_uploads"
    root.mkdir(parents=True, exist_ok=True)
    return root


def _request_upload_dir() -> Path:
    directory = _uploads_root() / str(uuid.uuid4())
    directory.mkdir(parents=True, exist_ok=True)
    return directory


def _sanitize_filename(name: str | None, fallback: str = "dataset.bin") -> str:
    candidate = Path((name or fallback).strip() or fallback).name
    cleaned = "".join(ch if ch.isalnum() or ch in {".", "_", "-"} else "_" for ch in candidate)
    cleaned = cleaned.strip("._") or fallback
    return cleaned


def _looks_like_url(value: str) -> bool:
    parsed = urlparse(value)
    return parsed.scheme in {"http", "https"} and bool(parsed.netloc)


def _download_dataset_url(url: str, upload_dir: Path) -> str:
    response = requests.get(url, timeout=1800)
    response.raise_for_status()

    parsed = urlparse(url)
    filename = _sanitize_filename(Path(parsed.path).name or "downloaded_dataset.bin")
    target = upload_dir / filename
    target.write_bytes(response.content)
    return str(target)


def _store_embedded_dataset(file_obj: Dict[str, Any], upload_dir: Path) -> str:
    filename = _sanitize_filename(
        file_obj.get("filename")
        or file_obj.get("name")
        or file_obj.get("original_filename")
        or file_obj.get("path")
        or "uploaded_dataset.bin"
    )

    target = upload_dir / filename
    kind = file_obj.get("kind")

    if kind == "downloadable_file" and file_obj.get("url"):
        return _download_dataset_url(str(file_obj["url"]), upload_dir)

    if isinstance(file_obj.get("data"), str) and file_obj.get("encoding", "base64") == "base64":
        target.write_bytes(base64.b64decode(file_obj["data"]))
        return str(target)

    raise ValueError("Uploaded dataset object must contain base64 data or a downloadable URL.")


def _parse_json_mapping(value: str | None) -> Dict[str, Any]:
    if not value:
        return {}
    try:
        parsed = json.loads(value)
    except ValueError:
        return {}
    return parsed if isinstance(parsed, dict) else {}


def _request_payload() -> Dict[str, Any] | None:
    payload = request.get_json(silent=True)
    if isinstance(payload, dict):
        return payload

    if not request.files and not request.form:
        return None

    params: Dict[str, Any] = {}
    params.update(_parse_json_mapping(request.form.get("metadata")))
    params.update(_parse_json_mapping(request.form.get("Params")))
    params.update(_parse_json_mapping(request.form.get("params")))

    query = (
        request.form.get("query")
        or request.form.get("text")
        or request.form.get("prompt")
        or request.form.get("task")
        or request.form.get("message")
        or ""
    )

    for key, value in request.form.items():
        if key in {"query", "text", "prompt", "task", "message", "metadata", "Params", "params"}:
            continue
        if key == INPUT_DATASETS_FIELD:
            params[key] = json.loads(value) if value.strip().startswith(("[", "{")) else value
        else:
            params.setdefault(key, value)

    uploaded_files: list[dict[str, Any]] = []
    for file_storage in request.files.values():
        filename = _sanitize_filename(file_storage.filename or "uploaded_dataset.bin")
        uploaded_files.append(
            {
                "filename": filename,
                "mime_type": file_storage.mimetype,
                "encoding": "base64",
                "data": base64.b64encode(file_storage.read()).decode("ascii"),
            }
        )
    if uploaded_files:
        existing = params.get(INPUT_DATASETS_FIELD)
        if isinstance(existing, list):
            params[INPUT_DATASETS_FIELD] = existing + uploaded_files
        elif existing:
            params[INPUT_DATASETS_FIELD] = [existing] + uploaded_files
        else:
            params[INPUT_DATASETS_FIELD] = uploaded_files

    return {
        "query": query,
        **params,
    }


def _normalize_input_datasets(value: Any) -> tuple[List[str], List[Dict[str, Any]]]:
    if value is None:
        return [], []
    items = value if isinstance(value, list) else [value]
    string_inputs: List[str] = []
    encoded_inputs: List[Dict[str, Any]] = []
    for item in items:
        if isinstance(item, str):
            string_inputs.extend(_normalize_input_dataset_strings(item))
        elif isinstance(item, dict):
            encoded_inputs.append(item)
    return string_inputs, encoded_inputs


def _materialize_dataset_inputs(
    input_dataset_strings: List[str],
    input_dataset_objects: List[Dict[str, Any]],
) -> List[str]:
    if not input_dataset_strings and not input_dataset_objects:
        return []

    upload_dir = _request_upload_dir()
    materialized: List[str] = []

    for input_dataset in input_dataset_strings:
        if _looks_like_url(input_dataset):
            materialized.append(_download_dataset_url(input_dataset, upload_dir))
        else:
            materialized.append(input_dataset)

    for file_obj in input_dataset_objects:
        materialized.append(_store_embedded_dataset(file_obj, upload_dir))

    return materialized


def _first_present(mapping: Dict[str, Any], field_names: Tuple[str, ...]) -> str | None:
    for field_name in field_names:
        value = mapping.get(field_name)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return None


def _gas_status_for_state(state: str) -> str:
    return STATE_TO_STATUS.get(state, state.lower())


def _is_terminal_state(state: str) -> bool:
    return _gas_status_for_state(state) in TERMINAL_STATUSES


def _extract_request_credentials(metadata: Dict[str, Any]) -> Dict[str, str | None]:
    return {
        "openai_api_key": _first_present(metadata, REQUEST_OPENAI_KEY_FIELDS),
        "gibd_api_key": _first_present(metadata, REQUEST_GIBD_KEY_FIELDS),
    }


def _extract_request_model(metadata: Dict[str, Any]) -> str | None:
    value = metadata.get("model")
    if isinstance(value, str) and value.strip():
        return value.strip()
    return None


def _extract_task_mode(payload: Dict[str, Any]) -> str:
    task = payload.get("task") if isinstance(payload.get("task"), dict) else {}
    mode = task.get("mode") or payload.get("mode") or "sync"
    if not isinstance(mode, str):
        raise ValueError("task.mode must be one of 'sync', 'async', or 'stream'.")
    normalized = mode.strip().lower()
    if normalized not in {"sync", "async", "stream"}:
        raise ValueError("task.mode must be one of 'sync', 'async', or 'stream'.")
    return normalized


def _gas_execute_task_to_run_payload(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Translate the GAS-native ExecuteTask body into the shared run payload."""
    task = payload.get("task") if isinstance(payload.get("task"), dict) else {}
    instructions = task.get("instructions") or payload.get("instructions")
    if not isinstance(instructions, str) or not instructions.strip():
        raise ValueError("task.instructions is required.")

    inputs = payload.get("inputs") if isinstance(payload.get("inputs"), dict) else {}
    outputs = payload.get("outputs") if isinstance(payload.get("outputs"), dict) else {}
    parameters = payload.get("parameters") if isinstance(payload.get("parameters"), dict) else {}
    credentials = payload.get("credentials") if isinstance(payload.get("credentials"), dict) else {}
    metadata = payload.get("metadata") if isinstance(payload.get("metadata"), dict) else {}

    params: Dict[str, Any] = {}
    params.update(metadata)
    params.update(parameters)
    params.update(credentials)

    if "input_datasets" in inputs:
        params["input_datasets"] = inputs.get("input_datasets")
    if "artifact_delivery" in outputs:
        params["output_delivery"] = outputs.get("artifact_delivery")
    for key, value in outputs.items():
        if key != "artifact_delivery":
            params.setdefault(key, value)

    params["mode"] = _extract_task_mode(payload)

    return {
        "query": instructions.strip(),
        "parameters": params,
        **params,
    }


def _build_agent_for_request(spec: AgentSpec, metadata: Dict[str, Any]) -> Any:
    model = _extract_request_model(metadata)
    if model:
        return spec.build_agent(model)
    return spec.build_agent()


def _extract_output_delivery(metadata: Dict[str, Any]) -> str:
    value = _first_present(metadata, REQUEST_OUTPUT_DELIVERY_FIELDS)
    if not value:
        return "url"

    normalized = value.strip().lower()
    if normalized in {"encoded", "url"}:
        return normalized
    raise ValueError("output_delivery must be either 'Encoded' or 'URL'.")


def _extract_stream_requested(metadata: Dict[str, Any]) -> bool:
    for field_name in REQUEST_STREAM_FIELDS:
        if field_name not in metadata:
            continue
        value = metadata.get(field_name)
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            return value.strip().lower() in {"true", "1", "yes", "y", "on"}
        return bool(value)
    return False


def _displayed_reasoning_message(stage: str, spec: AgentSpec, detail: str | None = None) -> str:
    templates = {
        "received": f"The user wants help from the {spec.agent_id}.",
        "inputs": "I need to inspect the request text and any provided dataset references before running the agent.",
        "credentials": "I found the required credentials and can start the model-backed workflow.",
        "agent_start": "Next I will run the agent with the prepared inputs.",
        "agent_done": "The agent finished its workflow, so I will normalize the result and prepare artifacts.",
        "failed": "The agent hit an issue, so I will return the error in the final diagnostics.",
    }
    message = templates.get(stage, detail or stage)
    if detail:
        return f"{message} {detail}"
    return message


def _call_agent_with_optional_progress(
    spec: AgentSpec,
    agent: Any,
    query: str,
    input_dataset_paths: List[str],
    progress_callback=None,
    parameters: Dict[str, Any] | None = None,
) -> Dict[str, Any]:
    if progress_callback is not None and spec.run_agent_with_progress is not None:
        return spec.run_agent_with_progress(
            agent,
            query,
            input_dataset_paths,
            progress_callback,
            parameters,
        )
    return spec.run_agent(agent, query, input_dataset_paths, parameters)


def _is_local_file_reference(value: str) -> bool:
    if not isinstance(value, str):
        return False

    cleaned = value.strip()
    if not cleaned:
        return False

    # Reject obvious non-path payloads before touching the filesystem.
    if len(cleaned) > 512:
        return False
    if cleaned.startswith(("{", "[")):
        return False
    if "://" in cleaned:
        return False
    if "\n" in cleaned or "\r" in cleaned:
        return False
    if "\x00" in cleaned:
        return False
    if not any(token in cleaned for token in (os.sep, "/", "\\", ".")):
        return False

    try:
        path = Path(cleaned).expanduser()
    except (TypeError, ValueError, OSError):
        return False

    try:
        return path.is_file()
    except OSError:
        return False


def _mime_type_for_path(path: Path) -> str:
    suffix = path.suffix.lower()
    overrides = {
        ".geojson": "application/geo+json",
        ".gpkg": "application/geopackage+sqlite3",
        ".shp": "application/octet-stream",
        ".tif": "image/tiff",
        ".tiff": "image/tiff",
    }
    if suffix in overrides:
        return overrides[suffix]
    guessed, _ = mimetypes.guess_type(path.name)
    return guessed or "application/octet-stream"


def _public_base_url(explicit_base_url: str | None = None) -> str:
    if explicit_base_url:
        return explicit_base_url.rstrip("/")
    if not has_request_context():
        return DEFAULT_PUBLIC_BASE_URL
    forwarded = request.headers.get("X-Proxy-Base-Url")
    if forwarded:
        return forwarded.rstrip("/")
    return request.host_url.rstrip("/")


def _public_agent_id(spec: AgentSpec) -> str:
    return request.headers.get("X-Proxy-Agent-Id", spec.agent_id)


def _agent_data_dir(agent_id: str) -> Path:
    ensure_runtime_dirs()
    directory = DATA_DIR / agent_id
    directory.mkdir(parents=True, exist_ok=True)
    return directory


def _generate_managed_filename(agent_id: str, original_path: Path) -> str:
    ext = original_path.suffix.lower()
    prefix = agent_id.replace(" ", "")
    letters = string.ascii_lowercase

    while True:
        candidate = (
            f"{prefix}-"
            f"{random.randint(0, 9999):04d}-"
            f"{''.join(random.choice(letters) for _ in range(4))}-"
            f"{random.randint(0, 9999):04d}"
            f"{ext}"
        )
        if not (_agent_data_dir(agent_id) / candidate).exists():
            return candidate


def _relocate_output_file(path_str: str, agent_id: str) -> Path:
    source = Path(path_str).expanduser()
    if not source.is_file():
        return source

    target_dir = _agent_data_dir(agent_id)
    if source.parent == target_dir and source.name.startswith(f"{agent_id}-"):
        return source

    target = target_dir / _generate_managed_filename(agent_id, source)
    shutil.move(str(source), str(target))
    return target


def _python_loader_example(filename: str, file_format: str | None, mime_type: str) -> tuple[str, str]:
    normalized_format = (file_format or "").lower()

    if normalized_format in {"geojson", "json", "gpkg", "shp", "gml", "kml"}:
        return (
            "Decode the base64 payload, write it to disk, then open it with GeoPandas.",
            "\n".join(
                [
                    "import base64",
                    "from pathlib import Path",
                    "import geopandas as gpd",
                    "",
                    "payload = embedded_file_object",
                    "output_path = Path(payload['filename'])",
                    "output_path.write_bytes(base64.b64decode(payload['data']))",
                    "gdf = gpd.read_file(output_path)",
                    "print(gdf.head())",
                ]
            ),
        )

    if normalized_format == "csv":
        return (
            "Decode the base64 payload, write it to disk, then open it with pandas.",
            "\n".join(
                [
                    "import base64",
                    "from pathlib import Path",
                    "import pandas as pd",
                    "",
                    "payload = embedded_file_object",
                    "output_path = Path(payload['filename'])",
                    "output_path.write_bytes(base64.b64decode(payload['data']))",
                    "df = pd.read_csv(output_path)",
                    "print(df.head())",
                ]
            ),
        )

    if normalized_format in {"tif", "tiff", "vrt", "img"} or mime_type == "image/tiff":
        return (
            "Decode the base64 payload, write it to disk, then open it with rasterio.",
            "\n".join(
                [
                    "import base64",
                    "from pathlib import Path",
                    "import rasterio",
                    "",
                    "payload = embedded_file_object",
                    "output_path = Path(payload['filename'])",
                    "output_path.write_bytes(base64.b64decode(payload['data']))",
                    "with rasterio.open(output_path) as src:",
                    "    print(src.count, src.width, src.height, src.crs)",
                ]
            ),
        )

    if normalized_format == "png" or mime_type == "image/png":
        return (
            "Decode the base64 payload, write it to disk, then open it with Pillow.",
            "\n".join(
                [
                    "import base64",
                    "from pathlib import Path",
                    "from PIL import Image",
                    "",
                    "payload = embedded_file_object",
                    "output_path = Path(payload['filename'])",
                    "output_path.write_bytes(base64.b64decode(payload['data']))",
                    "image = Image.open(output_path)",
                    "image.show()",
                ]
            ),
        )

    return (
        "Decode the base64 payload and write it to disk before opening it with the appropriate library.",
        "\n".join(
            [
                "import base64",
                "from pathlib import Path",
                "",
                "payload = embedded_file_object",
                "output_path = Path(payload['filename'])",
                "output_path.write_bytes(base64.b64decode(payload['data']))",
                "print(f\"Saved to {output_path}\")",
            ]
        ),
    )


def _build_file_payload(
    path: Path,
    *,
    output_delivery: str,
    agent_id: str,
    public_base_url: str | None = None,
) -> Dict[str, Any]:
    mime_type = _mime_type_for_path(path)
    base_payload = {
        "kind": "embedded_file",
        "filename": path.name,
        "format": path.suffix.lstrip(".").lower() or None,
        "mime_type": mime_type,
        "size_bytes": path.stat().st_size,
        "_local_path": str(path),
    }

    if output_delivery == "url":
        return {
            "kind": "downloadable_file",
            "filename": path.name,
            "format": base_payload["format"],
            "size_bytes": base_payload["size_bytes"],
            "url": f"{_public_base_url(public_base_url)}/agents/{agent_id}/data/{path.name}",
            "_local_path": str(path),
        }

    payload = path.read_bytes()
    how_to_open, python_loader_example = _python_loader_example(
        path.name,
        path.suffix.lstrip(".").lower() or None,
        mime_type,
    )
    return {
        **base_payload,
        "encoding": "base64",
        "data": base64.b64encode(payload).decode("ascii"),
        "how_to_open": how_to_open,
        "python_loader_example": python_loader_example,
    }


def _should_preserve_branch(ancestry: Tuple[str, ...]) -> bool:
    excluded_prefixes = (
        ("inputs",),
        ("complementary", "Execution", "Inputs"),
    )
    return any(ancestry[: len(prefix)] == prefix for prefix in excluded_prefixes)


def _transform_output_files(
    value: Any,
    *,
    agent_id: str,
    output_delivery: str,
    public_base_url: str | None = None,
    key_name: str = "",
    ancestry: Tuple[str, ...] = (),
) -> Any:
    if _should_preserve_branch(ancestry):
        return value

    if isinstance(value, str):
        key_lower = key_name.lower()
        if (
            _is_local_file_reference(value)
            and any(token in key_lower for token in ("path", "file", "output", "artifact", "downloaded"))
        ):
            original_path = Path(value).expanduser()
            relocated_path = _relocate_output_file(value, agent_id)
            payload = _build_file_payload(
                relocated_path,
                output_delivery=output_delivery,
                agent_id=agent_id,
                public_base_url=public_base_url,
            )
            payload["_original_filename"] = original_path.name
            payload["_original_path"] = str(original_path)
            return payload
        return value

    if isinstance(value, list):
        return [
            _transform_output_files(
                item,
                agent_id=agent_id,
                output_delivery=output_delivery,
                public_base_url=public_base_url,
                key_name=key_name,
                ancestry=ancestry,
            )
            for item in value
        ]

    if isinstance(value, dict):
        return {
            key: _transform_output_files(
                item,
                agent_id=agent_id,
                output_delivery=output_delivery,
                public_base_url=public_base_url,
                key_name=key,
                ancestry=ancestry + (key,),
            )
            for key, item in value.items()
        }

    return value


def _is_external_html_reference(reference: str) -> bool:
    if not reference:
        return True
    stripped = reference.strip()
    if stripped.startswith(("#", "data:", "mailto:", "tel:", "javascript:")):
        return True
    parsed = urlparse(stripped)
    return bool(parsed.scheme or parsed.netloc)


def _rewrite_html_file_references(result: Dict[str, Any] | None) -> None:
    if not isinstance(result, dict):
        return

    file_payloads = _collect_file_payloads(result)
    reference_urls: Dict[str, str] = {}
    for payload in file_payloads:
        url = payload.get("url")
        if not url:
            continue
        for key in ("filename", "_original_filename"):
            filename = payload.get(key)
            if filename:
                reference_urls[Path(str(filename)).name] = str(url)

    if not reference_urls:
        return

    def replacement(match: re.Match[str]) -> str:
        attr, quote, reference = match.group(1), match.group(2), match.group(3)
        if _is_external_html_reference(reference):
            return match.group(0)
        filename = Path(urlparse(reference).path).name
        public_url = reference_urls.get(filename)
        if not public_url:
            return match.group(0)
        return f"{attr}={quote}{public_url}{quote}"

    def css_replacement(match: re.Match[str]) -> str:
        quote, reference = match.group(1) or "", match.group(2)
        if _is_external_html_reference(reference):
            return match.group(0)
        filename = Path(urlparse(reference).path).name
        public_url = reference_urls.get(filename)
        if not public_url:
            return match.group(0)
        return f"url({quote}{public_url}{quote})"

    for payload in file_payloads:
        if (payload.get("format") or "").lower() not in {"html", "htm"}:
            continue
        local_path = Path(str(payload.get("_local_path") or ""))
        if not local_path.is_file():
            continue
        try:
            html = local_path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        rewritten = re.sub(r"\b(src|href)=(['\"])([^'\"]+)\2", replacement, html)
        rewritten = re.sub(r"url\((['\"]?)([^)'\"\s]+)\1\)", css_replacement, rewritten)
        if rewritten != html:
            local_path.write_text(rewritten, encoding="utf-8")


def _strip_dataset_paths(value: Any, ancestry: Tuple[str, ...] = ()) -> Any:
    if _should_preserve_branch(ancestry):
        return value
    if isinstance(value, list):
        return [_strip_dataset_paths(item, ancestry=ancestry) for item in value]
    if isinstance(value, dict):
        sanitized: Dict[str, Any] = {}
        for key, item in value.items():
            if key in DATASET_PATH_KEYS:
                if isinstance(item, dict) and item.get("kind") in {"embedded_file", "downloadable_file"}:
                    replacement_key = "dataset" if ancestry[:1] == ("outputs",) else key.replace("_path", "")
                    sanitized[replacement_key] = _strip_dataset_paths(item, ancestry=ancestry + (replacement_key,))
                elif isinstance(item, list) and all(
                    isinstance(part, dict) and part.get("kind") in {"embedded_file", "downloadable_file"}
                    for part in item
                ):
                    replacement_key = "datasets" if ancestry[:1] == ("outputs",) else key
                    sanitized[replacement_key] = _strip_dataset_paths(item, ancestry=ancestry + (replacement_key,))
                continue
            sanitized[key] = _strip_dataset_paths(item, ancestry=ancestry + (key,))
        return sanitized
    return value


def _extract_text_and_input_dataset_paths(payload: Dict[str, Any]) -> Tuple[str, List[str], Dict[str, Any], Dict[str, Any]]:
    raw_message = payload.get("message", payload)
    if isinstance(raw_message, str):
        message: Dict[str, Any] = {"parts": [{"kind": "text", "text": raw_message}]}
    elif isinstance(raw_message, dict):
        message = raw_message
    else:
        raise ValueError("Request body must contain task.instructions, query, or text.")

    # The GAS-native request path uses top-level query/parameters. The message,
    # Params, and parts branches remain as a compatibility adapter for older
    # local tests or direct service clients.
    params: Dict[str, Any] = {}
    if isinstance(payload.get("parameters"), dict):
        params.update(payload["parameters"])
    if isinstance(payload.get("metadata"), dict):
        params.update(payload["metadata"])
    if isinstance(payload.get("Params"), dict):
        params.update(payload["Params"])
    if isinstance(payload.get("params"), dict):
        params.update(payload["params"])
    if isinstance(message.get("parameters"), dict):
        params.update(message["parameters"])
    if isinstance(message.get("metadata"), dict):
        params.update(message["metadata"])
    if isinstance(message.get("Params"), dict):
        params.update(message["Params"])
    if isinstance(message.get("params"), dict):
        params.update(message["params"])
    for field_name in (
        REQUEST_OPENAI_KEY_FIELDS
        + REQUEST_GIBD_KEY_FIELDS
        + REQUEST_OUTPUT_DELIVERY_FIELDS
        + REQUEST_STREAM_FIELDS
        + (INPUT_DATASETS_FIELD, "mode", "model", "source_credentials")
    ):
        if field_name in payload and field_name not in params:
            params[field_name] = payload[field_name]
        if field_name in message and field_name not in params:
            params[field_name] = message[field_name]

    reserved_payload_fields = {"message", "parts", "task", "query", "text", "prompt", "content"}
    for key, value in payload.items():
        if key not in reserved_payload_fields and key not in params:
            params[key] = value

    parts = message.get("parts")
    if not isinstance(parts, list) or not parts:
        fallback_text = _first_present(
            {**payload, **message, **params},
            (
                "query",
                "text",
                "prompt",
                "task",
                "data_request",
                "user_query",
                "input",
                "content",
            ),
        )
        if fallback_text:
            parts = [{"kind": "text", "text": fallback_text}]
            message = {**message, "parts": parts}

    if not isinstance(parts, list) or not parts:
        raise ValueError("Message.parts must be a non-empty list.")

    text_parts: List[str] = []
    input_dataset_strings, input_dataset_objects = _normalize_input_datasets(params.get(INPUT_DATASETS_FIELD))

    for part in parts:
        if not isinstance(part, dict):
            continue

        if isinstance(part.get("text"), str):
            text_parts.append(part["text"])
        elif part.get("kind") == "text" and isinstance(part.get("data"), str):
            text_parts.append(part["data"])

        part_params = None
        if isinstance(part.get("Params"), dict):
            part_params = part["Params"]
        elif isinstance(part.get("params"), dict):
            part_params = part["params"]
        elif isinstance(part.get("metadata"), dict):
            part_params = part["metadata"]

        if isinstance(part_params, dict):
            for field_name in REQUEST_OPENAI_KEY_FIELDS + REQUEST_GIBD_KEY_FIELDS:
                if field_name in part_params and field_name not in params:
                    params[field_name] = part_params[field_name]
            part_strings, part_objects = _normalize_input_datasets(part_params.get(INPUT_DATASETS_FIELD))
            input_dataset_strings.extend(part_strings)
            input_dataset_objects.extend(part_objects)

        if part.get("kind") in {"file", "data"}:
            if isinstance(part.get("data"), dict):
                input_dataset_objects.append(part["data"])
            elif isinstance(part.get("file"), dict):
                input_dataset_objects.append(part["file"])

        for field_name in ("path", "uri", "url", "fileUri"):
            if part.get(field_name):
                input_dataset_strings.extend(_normalize_input_dataset_strings(part.get(field_name)))

    query = "\n".join(piece.strip() for piece in text_parts if piece and piece.strip()).strip()
    if not query:
        raise ValueError("Message.parts must include at least one text part.")

    requested_skill = (
        params.get("skill")
        or params.get("requested_skill")
        or params.get("skillId")
    )
    params["requested_skill"] = requested_skill
    input_dataset_paths = _materialize_dataset_inputs(input_dataset_strings, input_dataset_objects)
    return query, input_dataset_paths, params, message


def _extract_output_text(result: Dict[str, Any]) -> str:
    outputs = result.get("outputs", {})
    return str(outputs.get("text") or result.get("text") or "Task completed.")


def _extract_file_artifacts(result: Dict[str, Any]) -> List[Dict[str, Any]]:
    outputs = result.get("outputs", {})
    candidates: List[Tuple[str, Any]] = list(outputs.items()) if isinstance(outputs, dict) else []
    if isinstance(result, dict):
        candidates.extend((key, value) for key, value in result.items() if key != "outputs")

    seen = set()
    artifacts: List[Dict[str, Any]] = []
    for key, value in candidates:
        key_lower = key.lower()

        if isinstance(value, dict) and value.get("kind") in {"embedded_file", "downloadable_file"}:
            artifacts.append(
                {
                    "name": key,
                    "parts": [{"kind": "data", "data": value}],
                    "metadata": {
                        "filename": value.get("filename"),
                        "mime_type": value.get("mime_type"),
                        "url": value.get("url"),
                    },
                }
            )
            continue

        if isinstance(value, list) and any(
            isinstance(item, dict) and item.get("kind") in {"embedded_file", "downloadable_file"}
            for item in value
        ):
            artifacts.append(
                {
                    "name": key,
                    "parts": [
                        {"kind": "data", "data": item}
                        for item in value
                        if isinstance(item, dict) and item.get("kind") in {"embedded_file", "downloadable_file"}
                    ],
                    "metadata": {"count": len(value)},
                }
            )
            continue

        if not isinstance(value, str):
            continue
        if "path" not in key_lower and "file" not in key_lower and "output" not in key_lower:
            continue
        cleaned = value.strip()
        if not cleaned or cleaned in seen:
            continue
        if not _is_local_file_reference(cleaned):
            continue
        seen.add(cleaned)
        embedded = _embed_file_reference(cleaned)
        artifacts.append(
            {
                "name": key,
                "parts": [{"kind": "data", "data": embedded}],
                "metadata": {
                    "filename": embedded.get("filename"),
                    "mime_type": embedded.get("mime_type"),
                },
            }
        )
    return artifacts


def _nested_get(value: Dict[str, Any] | None, path: Tuple[str, ...], default: Any = None) -> Any:
    current: Any = value
    for key in path:
        if not isinstance(current, dict):
            return default
        current = current.get(key)
    return default if current is None else current


def _first_non_empty(*values: Any) -> Any:
    for value in values:
        if value not in (None, "", [], {}):
            return value
    return None


def _execution_status_for_state(state: str) -> str:
    if state == "TASK_STATE_COMPLETED":
        return "success"
    if state == "TASK_STATE_FAILED":
        return "failed"
    if state == "TASK_STATE_CANCELED":
        return "canceled"
    if state == "TASK_STATE_REJECTED":
        return "rejected"
    return "running"


def _summary_for_empty_result(state: str, error_message: str | None) -> str:
    if error_message:
        return ""
    if state == "TASK_STATE_SUBMITTED":
        return "Task submitted."
    if state == "TASK_STATE_WORKING":
        return "Task is running."
    return "Task completed."


def _collect_file_payloads(value: Any) -> List[Dict[str, Any]]:
    artifacts: List[Dict[str, Any]] = []
    if isinstance(value, dict):
        if value.get("kind") in {"embedded_file", "downloadable_file"}:
            artifacts.append(value)
        for item in value.values():
            artifacts.extend(_collect_file_payloads(item))
    elif isinstance(value, list):
        for item in value:
            artifacts.extend(_collect_file_payloads(item))
    return artifacts


def _normalize_artifacts(result: Dict[str, Any] | None) -> List[Dict[str, Any]]:
    if not isinstance(result, dict):
        return []

    normalized: List[Dict[str, Any]] = []
    seen: set[Tuple[Any, Any, Any]] = set()
    for index, payload in enumerate(_collect_file_payloads(result), start=1):
        key = (payload.get("filename"), payload.get("url"), payload.get("data"))
        if key in seen:
            continue
        seen.add(key)
        normalized.append(
            {
                "name": payload.get("filename") or f"artifact_{index}",
                "type": payload.get("kind"),
                "format": payload.get("format"),
                "mime_type": payload.get("mime_type"),
                "size_bytes": payload.get("size_bytes"),
                "url": payload.get("url"),
                "encoding": payload.get("encoding"),
                "data": payload.get("data"),
                **inspect_artifact(payload.get("_local_path")),
            }
        )
    return normalized


def _normalize_lineage(value: Any) -> List[Any]:
    if isinstance(value, list):
        return value
    if isinstance(value, dict):
        return list(value.values())
    if value:
        return [value]
    return []


def _normalize_data_summary(value: Any) -> Dict[str, Any]:
    if not isinstance(value, dict):
        return {"type": None, "dimensions": None, "feature_count": None}
    return {
        "type": value.get("type"),
        "dimensions": value.get("dimensions"),
        "feature_count": value.get("feature_count"),
    }


def _combined_bbox(bboxes: List[List[float]]) -> List[float] | None:
    if not bboxes:
        return None
    return [
        min(bbox[0] for bbox in bboxes),
        min(bbox[1] for bbox in bboxes),
        max(bbox[2] for bbox in bboxes),
        max(bbox[3] for bbox in bboxes),
    ]


def _valid_summary_bbox(value: Any) -> bool:
    return (
        isinstance(value, list)
        and len(value) == 4
        and all(isinstance(item, (int, float)) for item in value)
        and value[0] <= value[2]
        and value[1] <= value[3]
    )


def _summarize_artifact_metadata(artifacts: List[Dict[str, Any]], legacy_summary: Any = None) -> Dict[str, Any]:
    artifact_types: set[str] = set()
    formats: set[str] = set()
    crs_values: set[str] = set()
    bboxes: List[List[float]] = []
    feature_count_total = 0
    has_feature_counts = False
    has_spatial_metadata = False

    for artifact in artifacts:
        if artifact.get("format"):
            formats.add(str(artifact["format"]))
        metadata = artifact.get("spatial_metadata")
        if not isinstance(metadata, dict):
            continue
        has_spatial_metadata = True
        artifact_type = metadata.get("type")
        if artifact_type:
            artifact_types.add(str(artifact_type))
        crs = metadata.get("crs")
        if crs:
            crs_values.add(str(crs))
        bbox = metadata.get("bbox")
        if _valid_summary_bbox(bbox):
            bboxes.append([float(value) for value in bbox])
        feature_count = metadata.get("feature_count")
        if isinstance(feature_count, (int, float)) and not isinstance(feature_count, bool):
            feature_count_total += int(feature_count)
            has_feature_counts = True

    legacy = _normalize_data_summary(legacy_summary)
    primary_type = _first_non_empty(
        legacy.get("type"),
        next(iter(sorted(artifact_types)), None),
    )
    primary_dimensions = legacy.get("dimensions")
    primary_feature_count = _first_non_empty(
        legacy.get("feature_count"),
        feature_count_total if has_feature_counts else None,
    )

    return {
        "type": primary_type,
        "dimensions": primary_dimensions,
        "feature_count": primary_feature_count,
        "artifact_count": len(artifacts),
        "artifact_types": sorted(artifact_types),
        "formats": sorted(formats),
        "crs": sorted(crs_values),
        "combined_bbox": _combined_bbox(bboxes),
        "has_vector": "vector" in artifact_types,
        "has_raster": "raster" in artifact_types,
        "has_table": "table" in artifact_types,
        "feature_count_total": feature_count_total if has_feature_counts else None,
        "has_spatial_metadata": has_spatial_metadata,
    }


def _normalize_execution_inputs(value: Any) -> Dict[str, Any]:
    if not isinstance(value, dict):
        return {"dataset_paths": [], "parameters": {}}
    dataset_paths = _first_non_empty(
        value.get("dataset_paths"),
        value.get("dataset_path"),
        value.get("input_dataset_path"),
        value.get("datasets"),
        [],
    )
    if not isinstance(dataset_paths, list):
        dataset_paths = [dataset_paths]
    dataset_paths = [path for path in dataset_paths if path is not None]
    parameters = value.get("parameters") if isinstance(value.get("parameters"), dict) else {}
    return {
        "dataset_paths": dataset_paths,
        "parameters": parameters,
    }


def _merge_execution_inputs(primary: Any, fallback: Any) -> Dict[str, Any]:
    primary_inputs = _normalize_execution_inputs(primary)
    fallback_inputs = _normalize_execution_inputs(fallback)
    dataset_paths = _first_non_empty(primary_inputs.get("dataset_paths"), fallback_inputs.get("dataset_paths"), [])
    if dataset_paths is None:
        dataset_paths = []
    if not isinstance(dataset_paths, list):
        dataset_paths = [dataset_paths]
    parameters = {}
    if isinstance(fallback_inputs.get("parameters"), dict):
        parameters.update(fallback_inputs["parameters"])
    if isinstance(primary_inputs.get("parameters"), dict):
        parameters.update(primary_inputs["parameters"])
    return {
        "dataset_paths": dataset_paths,
        "parameters": parameters,
    }


def _normalize_runtime(value: Any) -> Dict[str, Any]:
    runtime = value if isinstance(value, dict) else {}
    libraries = _first_non_empty(
        runtime.get("domain-specific_libraries"),
        runtime.get("domain-specific libraries"),
        runtime.get("domain_specific_libraries"),
        [],
    )
    if not isinstance(libraries, list):
        libraries = [libraries]
    return {
        "python_version": runtime.get("python_version"),
        "domain-specific_libraries": libraries,
    }


def _extract_count(value: Any) -> Any:
    if isinstance(value, dict):
        return _first_non_empty(value.get("count"), value.get("total"), value.get("value"))
    return value


def _normalize_token_usage(result: Dict[str, Any]) -> Dict[str, Any]:
    input_tokens = result.get("total_input_tokens")
    output_tokens = _first_non_empty(result.get("total_output_tokens"), result.get("toatal_output_tokens"))
    total_tokens = _first_non_empty(result.get("total_tokens"), (input_tokens + output_tokens) if isinstance(input_tokens, int) and isinstance(output_tokens, int) else None)
    return {
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "total_tokens": total_tokens,
    }


def _normalize_iterations(result: Dict[str, Any], metrics: Dict[str, Any], llm_calls: Any, tool_calls: Any) -> Any:
    return _first_non_empty(
        result.get("iterations"),
        metrics.get("iterations"),
        llm_calls,
        tool_calls,
        0,
    )


def _normalize_diagnostics(error_message: str | None, complementary: Dict[str, Any]) -> Dict[str, Any]:
    validation = complementary.get("Validation") if isinstance(complementary.get("Validation"), dict) else {}
    assumptions_limitations = (
        complementary.get("Assumptions and Limitations")
        if isinstance(complementary.get("Assumptions and Limitations"), dict)
        else {}
    )
    warnings: List[str] = []
    for key in ("warnings", "limitations"):
        values = assumptions_limitations.get(key)
        if isinstance(values, list):
            warnings.extend(str(value) for value in values if value)
        elif values:
            warnings.append(str(values))

    return {
        "has_error": bool(error_message),
        "error": error_message,
        "warnings": warnings,
        "validation": validation,
        "assumptions": assumptions_limitations.get("assumptions", []),
        "limitations": assumptions_limitations.get("limitations", []),
    }


def _normalize_reproducibility(
    *,
    execution_inputs: Dict[str, Any],
    runtime: Dict[str, Any],
    normalized_artifacts: List[Dict[str, Any]],
    code: Dict[str, Any],
    result: Dict[str, Any],
) -> Dict[str, Any]:
    input_artifacts = [
        {
            "role": "input",
            "path": path,
        }
        for path in execution_inputs.get("dataset_paths", [])
    ]
    output_artifacts = [
        {
            "role": "output",
            "name": artifact.get("name"),
            "url": artifact.get("url"),
            "format": artifact.get("format"),
            "type": artifact.get("type"),
        }
        for artifact in normalized_artifacts
    ]
    stochasticity = result.get("stochasticity") if isinstance(result.get("stochasticity"), dict) else {}
    return {
        "code_available": bool(code.get("available")),
        "environment_available": bool(runtime.get("python_version") or runtime.get("domain-specific_libraries")),
        "parameters_available": bool(execution_inputs.get("parameters")),
        "input_artifacts": input_artifacts,
        "output_artifacts": output_artifacts,
        "parameters": execution_inputs.get("parameters", {}),
        "stochasticity": {
            "used": stochasticity.get("used", "unknown"),
            "controls": stochasticity.get("controls", []),
        },
        "notes": result.get("reproducibility_notes") if isinstance(result.get("reproducibility_notes"), list) else [],
    }


def _parse_duration_seconds(value: Any) -> float | None:
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        match = re.search(r"[-+]?\d*\.?\d+", value)
        if match:
            try:
                return float(match.group(0))
            except ValueError:
                return None
    return None


def _normalize_agent_result(
    *,
    task_id: str,
    agent_id: str,
    agent_name: str | None,
    agent_version: str | None,
    state: str,
    query: str,
    requested_skill: str | None,
    result: Dict[str, Any] | None,
    error_message: str | None,
    output_delivery: str,
    created_at: str,
    completed_at: str,
) -> Dict[str, Any]:
    result = result if isinstance(result, dict) else {}
    result = {key: value for key, value in result.items() if key not in {"events", "stream_events", "thinking_events"}}
    outputs = result.get("outputs") if isinstance(result.get("outputs"), dict) else {}
    outputs = {key: value for key, value in outputs.items() if key not in {"events", "stream_events", "thinking_events"}}
    metrics = result.get("metrics") if isinstance(result.get("metrics"), dict) else {}
    complementary = result.get("complementary") if isinstance(result.get("complementary"), dict) else {}
    complementary_outputs = _nested_get(complementary, ("Execution", "Outputs"), {})
    complementary_inputs = _nested_get(complementary, ("Execution", "Inputs"), {})
    complementary_provenance = _nested_get(complementary, ("Provenance",), {})
    environment = result.get("environment") if isinstance(result.get("environment"), dict) else {}
    normalized_artifacts = _normalize_artifacts(result)
    data_summary = _summarize_artifact_metadata(
        normalized_artifacts,
        _first_non_empty(outputs.get("dataset_size"), result.get("dataset_size"), {}),
    )
    execution_inputs = _merge_execution_inputs(complementary_inputs, result.get("inputs"))
    runtime = _normalize_runtime(environment)
    llm_calls = _first_non_empty(
        metrics.get("llm_calls"),
        _extract_count(_nested_get(complementary_provenance, ("LLM Calls",), None)),
        result.get("llm_calls"),
    )
    tool_calls = _first_non_empty(
        metrics.get("tool_calls"),
        _extract_count(_nested_get(complementary_provenance, ("Tool Calls",), None)),
        result.get("tool_calls"),
    )
    token_usage = _normalize_token_usage(result)
    duration_seconds = _parse_duration_seconds(result.get("duration"))
    iterations = _normalize_iterations(result, metrics, llm_calls, tool_calls)
    code = {
        "available": bool(result.get("script")),
        "language": "python" if result.get("script") else None,
        "script": result.get("script"),
    }
    reproducibility = _normalize_reproducibility(
        execution_inputs=execution_inputs,
        runtime=runtime,
        normalized_artifacts=normalized_artifacts,
        code=code,
        result=result,
    )

    return {
        "response": {
            "type": "task_result",
            "schema_version": "1.0.0",
            "created_at": created_at,
            "completed_at": completed_at,
        },
        "task": {
            "id": task_id,
            "status": _gas_status_for_state(state),
            "terminal": _is_terminal_state(state),
            "user_request": query,
            "requested_skill": requested_skill,
            "artifact_delivery": "Encoded" if output_delivery == "encoded" else "URL",
        },
        "agent": {
            "id": agent_id,
            "name": _first_non_empty(result.get("agent_name"), agent_name),
            "version": _first_non_empty(result.get("agent_version"), agent_version),
            "model": result.get("model"),
        },
        "outputs": {
            "summary": _first_non_empty(
                outputs.get("text"),
                complementary_outputs.get("summary") if isinstance(complementary_outputs, dict) else None,
                result.get("text"),
                _summary_for_empty_result(state, error_message),
            ),
            "artifacts": normalized_artifacts,
            "data_summary": data_summary,
        },
        "execution": {
            "status": _execution_status_for_state(state),
            "duration_seconds": duration_seconds,
            "iterations": iterations,
            "inputs": execution_inputs,
            "code": code,
            "runtime": runtime,
        },
        "provenance": {
            "llm_calls": llm_calls or 0,
            "tool_calls": tool_calls or 0,
            "artifacts_created": _first_non_empty(
                metrics.get("number_of_artifacts"),
                metrics.get("number of artifacts"),
                len(normalized_artifacts),
            ),
            "token_usage": token_usage,
            "lineage": _normalize_lineage(_nested_get(complementary_provenance, ("Lineage",), [])),
        },
        "reproducibility": reproducibility,
        "diagnostics": _normalize_diagnostics(error_message, complementary),
    }


def _remove_stream_event_fields(value: Any) -> Any:
    stream_event_keys = {"events", "stream_events", "thinking_events"}
    if isinstance(value, dict):
        return {
            key: _remove_stream_event_fields(item)
            for key, item in value.items()
            if key not in stream_event_keys
        }
    if isinstance(value, list):
        return [_remove_stream_event_fields(item) for item in value]
    return value


def _build_task_payload(
    *,
    task_id: str,
    agent_id: str,
    agent_name: str | None,
    agent_version: str | None,
    state: str,
    query: str,
    requested_skill: str | None,
    result: Dict[str, Any] | None,
    error_message: str | None,
    agent_id_for_artifacts: str,
    output_delivery: str,
    public_base_url: str | None = None,
) -> Dict[str, Any]:
    transformed_result = (
        _transform_output_files(
            result,
            agent_id=agent_id_for_artifacts,
            output_delivery=output_delivery,
            public_base_url=public_base_url,
        )
        if result is not None
        else None
    )
    _rewrite_html_file_references(transformed_result)
    normalized_result = _strip_dataset_paths(transformed_result) if transformed_result is not None else None

    completed_dt = datetime.now(timezone.utc)
    duration_seconds = _parse_duration_seconds(normalized_result.get("duration") if isinstance(normalized_result, dict) else None)
    created_dt = completed_dt - timedelta(seconds=duration_seconds) if duration_seconds and _is_terminal_state(state) else completed_dt
    created_at = created_dt.isoformat()
    completed_at = completed_dt.isoformat() if _is_terminal_state(state) else None
    task_payload = _normalize_agent_result(
        task_id=task_id,
        agent_id=agent_id,
        agent_name=agent_name,
        agent_version=agent_version,
        state=state,
        query=query,
        requested_skill=requested_skill,
        result=normalized_result,
        error_message=error_message,
        output_delivery=output_delivery,
        created_at=created_at,
        completed_at=completed_at,
    )
    return _remove_stream_event_fields(task_payload)


def init_service_state() -> Dict[str, Any]:
    return {"TASKS": {}, "CLOSED_TASKS": set(), "LOCK": threading.RLock()}


def build_agent_card(spec: AgentSpec) -> Dict[str, Any]:
    card_agent = spec.build_agent()
    describe_agent = load_describe_agent_json(spec) or {}
    profile = describe_agent.get("profile") if isinstance(describe_agent.get("profile"), dict) else {}
    skills = describe_agent.get("skills") if isinstance(describe_agent.get("skills"), list) else []
    return {
        "name": profile.get("name") or spec.get_name(card_agent),
        "description": profile.get("description") or "",
        "version": profile.get("version") or spec.get_version(card_agent),
        "agentId": profile.get("agent_id") or spec.agent_id,
        "supportedInterfaces": [
            {
                "url": f"/agents/{spec.agent_id}/tasks",
                "operation": "ExecuteTask",
            }
        ],
        "defaultInputModes": ["text"],
        "defaultOutputModes": ["text", "data"],
        "capabilities": {
            "streaming": True,
            "pushNotifications": False,
            "extendedAgentCard": False,
        },
        "skills": skills,
    }


def store_task(state: Dict[str, Any], task: Dict[str, Any]) -> Dict[str, Any]:
    task_id = task["task"]["id"]
    task_status = task["task"].get("status")
    lock = state.get("LOCK")
    if lock is None:
        state["TASKS"][task_id] = task
        if task_status in TERMINAL_STATUSES:
            state["CLOSED_TASKS"].add(task_id)
        return task

    with lock:
        state["TASKS"][task_id] = task
        if task_status in TERMINAL_STATUSES:
            state["CLOSED_TASKS"].add(task_id)
    return task


def _task_status(state: Dict[str, Any], task_id: str) -> str | None:
    lock = state.get("LOCK")
    if lock is None:
        task = state["TASKS"].get(task_id)
        return task.get("task", {}).get("status") if isinstance(task, dict) else None

    with lock:
        task = state["TASKS"].get(task_id)
        return task.get("task", {}).get("status") if isinstance(task, dict) else None


def _task_is_closed(state: Dict[str, Any], task_id: str) -> bool:
    lock = state.get("LOCK")
    if lock is None:
        return task_id in state["CLOSED_TASKS"]

    with lock:
        return task_id in state["CLOSED_TASKS"]


def _run_submitted_task_in_background(
    *,
    spec: AgentSpec,
    state: Dict[str, Any],
    task_id: str,
    query: str,
    dataset_paths: List[str],
    requested_skill: str | None,
    credentials: Dict[str, str | None],
    parameters: Dict[str, Any],
    output_delivery: str,
    public_agent_id: str,
    public_base_url: str,
    version: str,
) -> None:
    try:
        if _task_status(state, task_id) in TERMINAL_STATUSES or _task_is_closed(state, task_id):
            return

        running_task = _build_task_payload(
            task_id=task_id,
            agent_id=spec.agent_id,
            agent_name=None,
            agent_version=None,
            state="TASK_STATE_WORKING",
            query=query,
            requested_skill=requested_skill,
            result=None,
            error_message=None,
            agent_id_for_artifacts=public_agent_id,
            output_delivery=output_delivery,
            public_base_url=public_base_url,
        )
        store_task(state, running_task)

        agent = _build_agent_for_request(spec, parameters)
        agent_name = spec.get_name(agent)
        agent_version = spec.get_version(agent)
        _configure_agent_client_if_available(
            agent,
            agent_name=agent_name,
            credentials=credentials,
        )
        result = _call_agent_with_optional_progress(
            spec,
            agent,
            query,
            dataset_paths,
            parameters=parameters,
        )

        if _task_status(state, task_id) in TERMINAL_STATUSES or _task_is_closed(state, task_id):
            return

        completed_task = _build_task_payload(
            task_id=task_id,
            agent_id=spec.agent_id,
            agent_name=agent_name,
            agent_version=agent_version,
            state="TASK_STATE_COMPLETED",
            query=query,
            requested_skill=requested_skill,
            result=result,
            error_message=None,
            agent_id_for_artifacts=public_agent_id,
            output_delivery=output_delivery,
            public_base_url=public_base_url,
        )
        store_task(state, completed_task)
    except Exception as exc:
        if _task_status(state, task_id) in TERMINAL_STATUSES or _task_is_closed(state, task_id):
            return

        failed_task = _build_task_payload(
            task_id=task_id,
            agent_id=spec.agent_id,
            agent_name=None,
            agent_version=None,
            state="TASK_STATE_FAILED",
            query=query,
            requested_skill=requested_skill,
            result=None,
            error_message=str(exc),
            agent_id_for_artifacts=public_agent_id,
            output_delivery=output_delivery,
            public_base_url=public_base_url,
        )
        store_task(state, failed_task)


def submit_agent_task_from_payload(spec: AgentSpec, state: Dict[str, Any], payload: Dict[str, Any], version: str) -> Response:
    try:
        query, dataset_paths, metadata, _message = _extract_text_and_input_dataset_paths(payload)
    except ValueError as exc:
        return _gas_error(
            "INVALID_ARGUMENT",
            str(exc),
            status_code=HTTPStatus.BAD_REQUEST,
            version=version,
        )

    referenced_task_id = metadata.get("taskId") or metadata.get("task_id") or payload.get("taskId")
    if referenced_task_id and referenced_task_id in state["CLOSED_TASKS"]:
        return _gas_error(
            "TASK_CLOSED",
            f"Task '{referenced_task_id}' is already closed.",
            status_code=HTTPStatus.CONFLICT,
            version=version,
        )

    validation_error = spec.validate_inputs(dataset_paths)
    if validation_error:
        return _gas_error(
            "INVALID_ARGUMENT",
            validation_error,
            status_code=HTTPStatus.BAD_REQUEST,
            version=version,
        )

    credentials = _extract_request_credentials(metadata)
    if _requires_model_credentials(spec) and not _has_model_credentials(credentials):
        return _gas_error(
            "INVALID_ARGUMENT",
            "Request credentials must include either OPENAI_API_KEY or GIBD_API_KEY.",
            status_code=HTTPStatus.BAD_REQUEST,
            version=version,
        )

    try:
        output_delivery = _extract_output_delivery(metadata)
    except ValueError as exc:
        return _gas_error(
            "INVALID_ARGUMENT",
            str(exc),
            status_code=HTTPStatus.BAD_REQUEST,
            version=version,
        )

    task_id = str(uuid.uuid4())
    requested_skill = metadata.get("requested_skill")
    public_agent_id = _public_agent_id(spec)
    public_base_url = _public_base_url()
    submitted_task = _build_task_payload(
        task_id=task_id,
        agent_id=spec.agent_id,
        agent_name=None,
        agent_version=None,
        state="TASK_STATE_SUBMITTED",
        query=query,
        requested_skill=requested_skill,
        result=None,
        error_message=None,
        agent_id_for_artifacts=public_agent_id,
        output_delivery=output_delivery,
        public_base_url=public_base_url,
    )
    store_task(state, submitted_task)

    worker = threading.Thread(
        target=_run_submitted_task_in_background,
        kwargs={
            "spec": spec,
            "state": state,
            "task_id": task_id,
            "query": query,
            "dataset_paths": dataset_paths,
            "requested_skill": requested_skill,
            "credentials": credentials,
            "parameters": metadata,
            "output_delivery": output_delivery,
            "public_agent_id": public_agent_id,
            "public_base_url": public_base_url,
            "version": version,
        },
        daemon=True,
    )
    worker.start()

    response = _json_response(submitted_task, HTTPStatus.ACCEPTED, version)
    response.headers["Location"] = f"/tasks/{task_id}/status"
    return response


def run_agent_from_payload(spec: AgentSpec, state: Dict[str, Any], payload: Dict[str, Any], version: str) -> Response:
    try:
        query, dataset_paths, metadata, _message = _extract_text_and_input_dataset_paths(payload)
    except ValueError as exc:
        return _gas_error(
            "INVALID_ARGUMENT",
            str(exc),
            status_code=HTTPStatus.BAD_REQUEST,
            version=version,
        )

    referenced_task_id = metadata.get("taskId") or metadata.get("task_id") or payload.get("taskId")
    if referenced_task_id and referenced_task_id in state["CLOSED_TASKS"]:
        return _gas_error(
            "TASK_CLOSED",
            f"Task '{referenced_task_id}' is already closed.",
            status_code=HTTPStatus.CONFLICT,
            version=version,
        )

    validation_error = spec.validate_inputs(dataset_paths)
    if validation_error:
        return _gas_error(
            "INVALID_ARGUMENT",
            validation_error,
            status_code=HTTPStatus.BAD_REQUEST,
            version=version,
        )

    task_id = str(uuid.uuid4())
    requested_skill = metadata.get("requested_skill")
    credentials = _extract_request_credentials(metadata)
    try:
        output_delivery = _extract_output_delivery(metadata)
    except ValueError as exc:
        return _gas_error(
            "INVALID_ARGUMENT",
            str(exc),
            status_code=HTTPStatus.BAD_REQUEST,
            version=version,
        )

    if _requires_model_credentials(spec) and not _has_model_credentials(credentials):
        return _gas_error(
            "INVALID_ARGUMENT",
            "Request credentials must include either OPENAI_API_KEY or GIBD_API_KEY.",
            status_code=HTTPStatus.BAD_REQUEST,
            version=version,
        )

    try:
        agent = _build_agent_for_request(spec, metadata)
        agent_name = spec.get_name(agent)
        agent_version = spec.get_version(agent)
        _configure_agent_client_if_available(
            agent,
            agent_name=agent_name,
            credentials=credentials,
        )
        result = _call_agent_with_optional_progress(
            spec,
            agent,
            query,
            dataset_paths,
            parameters=metadata,
        )
        task = _build_task_payload(
            task_id=task_id,
            agent_id=spec.agent_id,
            agent_name=agent_name,
            agent_version=agent_version,
            state="TASK_STATE_COMPLETED",
            query=query,
            requested_skill=requested_skill,
            result=result,
            error_message=None,
            agent_id_for_artifacts=_public_agent_id(spec),
            output_delivery=output_delivery,
            public_base_url=_public_base_url(),
        )
        return _json_response(store_task(state, task), HTTPStatus.OK, version)
    except Exception as exc:
        task = _build_task_payload(
            task_id=task_id,
            agent_id=spec.agent_id,
            agent_name=None,
            agent_version=None,
            state="TASK_STATE_FAILED",
            query=query,
            requested_skill=requested_skill,
            result=None,
            error_message=str(exc),
            agent_id_for_artifacts=_public_agent_id(spec),
            output_delivery=output_delivery,
            public_base_url=_public_base_url(),
        )
        return _json_response(store_task(state, task), HTTPStatus.INTERNAL_SERVER_ERROR, version)


def stream_agent_from_payload(spec: AgentSpec, state: Dict[str, Any], payload: Dict[str, Any], version: str) -> Response:
    stream_debug_id = str(uuid.uuid4())
    _record_stream_debug(
        "stream_response_created",
        stream_debug_id=stream_debug_id,
        agent_id=spec.agent_id,
        path=request.path,
        stream_param_seen=True,
    )

    def _event_stream():
        import time

        _record_stream_debug("generator_entered", stream_debug_id=stream_debug_id, agent_id=spec.agent_id)
        stream_agent_id = _public_agent_id(spec)
        stream_base_url = _public_base_url()
        flush_padding = " " * 2048

        def _make_event(kind: str, **data: Any) -> Dict[str, Any]:
            event = {
                "event": kind,
                "timestamp": _iso_now(),
                **data,
            }
            if kind != "task_result":
                event["_flush"] = flush_padding
            return event

        def _yield_event(kind: str, **data: Any):
            event = _make_event(kind, **data)
            line = json.dumps(event) + "\n"
            _record_stream_debug(
                "yield_before",
                stream_debug_id=stream_debug_id,
                stream_event=kind,
                message=data.get("message"),
                line_bytes=len(line.encode("utf-8")),
            )
            yield line
            _record_stream_debug(
                "yield_after",
                stream_debug_id=stream_debug_id,
                stream_event=kind,
                message=data.get("message"),
            )
            time.sleep(0.1)

        def _reason(stage: str, detail: str | None = None) -> Dict[str, Any]:
            return _make_event(
                "progress",
                message=_displayed_reasoning_message(stage, spec, detail),
            )

        progress_events: List[Dict[str, Any]] = []

        def _progress_callback(event: Dict[str, Any]) -> None:
            message = event.get("message") if isinstance(event, dict) else None
            stage = event.get("stage") if isinstance(event, dict) else None
            _record_stream_debug(
                "mapping_progress_callback",
                stream_debug_id=stream_debug_id,
                stage=stage,
                message=message,
            )
            progress_events.append(
                _make_event(
                    "progress",
                    message=message or "The mapping agent reported a workflow update.",
                    stage=stage,
                    payload=event,
                )
            )

        yield from _yield_event(
            "stream_connected",
            status="accepted",
            message="Streaming connection established.",
            payload={},
        )

        try:
            _record_stream_debug("extract_inputs_start", stream_debug_id=stream_debug_id)
            query, dataset_paths, metadata, _message = _extract_text_and_input_dataset_paths(payload)
            _record_stream_debug(
                "extract_inputs_done",
                stream_debug_id=stream_debug_id,
                dataset_count=len(dataset_paths),
            )
            reason_event = _reason("received")
            _record_stream_debug(
                "yield_before",
                stream_debug_id=stream_debug_id,
                stream_event=reason_event.get("event"),
                message=reason_event.get("message"),
                line_bytes=len((json.dumps(reason_event) + "\n").encode("utf-8")),
            )
            yield json.dumps(reason_event) + "\n"
            _record_stream_debug(
                "yield_after",
                stream_debug_id=stream_debug_id,
                stream_event=reason_event.get("event"),
                message=reason_event.get("message"),
            )
            time.sleep(0.1)
            reason_event = _reason("inputs", f"I found {len(dataset_paths)} dataset reference(s).")
            _record_stream_debug(
                "yield_before",
                stream_debug_id=stream_debug_id,
                stream_event=reason_event.get("event"),
                message=reason_event.get("message"),
                line_bytes=len((json.dumps(reason_event) + "\n").encode("utf-8")),
            )
            yield json.dumps(reason_event) + "\n"
            _record_stream_debug(
                "yield_after",
                stream_debug_id=stream_debug_id,
                stream_event=reason_event.get("event"),
                message=reason_event.get("message"),
            )
            time.sleep(0.1)
        except ValueError as exc:
            yield from _yield_event(
                "task_failed",
                status="failed",
                status_code=HTTPStatus.BAD_REQUEST,
                payload={"error": {"code": "INVALID_ARGUMENT", "message": str(exc)}},
            )
            return

        referenced_task_id = metadata.get("taskId") or metadata.get("task_id") or payload.get("taskId")
        if referenced_task_id and referenced_task_id in state["CLOSED_TASKS"]:
            yield from _yield_event(
                "task_failed",
                status="failed",
                status_code=HTTPStatus.CONFLICT,
                payload={
                    "error": {
                        "code": "TASK_CLOSED",
                        "message": f"Task '{referenced_task_id}' is already closed.",
                    }
                },
            )
            return

        validation_error = spec.validate_inputs(dataset_paths)
        if validation_error:
            yield from _yield_event(
                "task_failed",
                status="failed",
                status_code=HTTPStatus.BAD_REQUEST,
                payload={"error": {"code": "INVALID_ARGUMENT", "message": validation_error}},
            )
            return

        credentials = _extract_request_credentials(metadata)
        if _requires_model_credentials(spec) and not _has_model_credentials(credentials):
            yield from _yield_event(
                "task_failed",
                status="failed",
                status_code=HTTPStatus.BAD_REQUEST,
                payload={
                    "error": {
                        "code": "INVALID_ARGUMENT",
                        "message": "Request credentials must include either OPENAI_API_KEY or GIBD_API_KEY.",
                    }
                },
            )
            return

        try:
            output_delivery = _extract_output_delivery(metadata)
        except ValueError as exc:
            yield from _yield_event(
                "task_failed",
                status="failed",
                status_code=HTTPStatus.BAD_REQUEST,
                payload={"error": {"code": "INVALID_ARGUMENT", "message": str(exc)}},
            )
            return

        task_id = str(uuid.uuid4())
        requested_skill = metadata.get("requested_skill")
        submitted_task = _build_task_payload(
            task_id=task_id,
            agent_id=spec.agent_id,
            agent_name=None,
            agent_version=None,
            state="TASK_STATE_SUBMITTED",
            query=query,
            requested_skill=requested_skill,
            result=None,
            error_message=None,
            agent_id_for_artifacts=stream_agent_id,
            output_delivery=output_delivery,
            public_base_url=stream_base_url,
        )
        store_task(state, submitted_task)
        _record_stream_debug("validation_and_credentials_done", stream_debug_id=stream_debug_id, task_id=task_id)
        if _has_model_credentials(credentials):
            reason_event = _reason("credentials")
        else:
            reason_event = _reason(
                "credentials_optional",
                "This agent can run deterministically without model credentials. If credentials are provided, they may be used for optional model-assisted fallback.",
            )
        _record_stream_debug(
            "yield_before",
            stream_debug_id=stream_debug_id,
            stream_event=reason_event.get("event"),
            message=reason_event.get("message"),
            line_bytes=len((json.dumps(reason_event) + "\n").encode("utf-8")),
        )
        yield json.dumps(reason_event) + "\n"
        _record_stream_debug(
            "yield_after",
            stream_debug_id=stream_debug_id,
            stream_event=reason_event.get("event"),
            message=reason_event.get("message"),
        )
        time.sleep(0.1)
        yield from _yield_event(
            "task_accepted",
            status="accepted",
            task_id=task_id,
            message="Task accepted. Starting streaming execution.",
            payload={"task_id": task_id},
        )

        try:
            running_task = _build_task_payload(
                task_id=task_id,
                agent_id=spec.agent_id,
                agent_name=None,
                agent_version=None,
                state="TASK_STATE_WORKING",
                query=query,
                requested_skill=requested_skill,
                result=None,
                error_message=None,
                agent_id_for_artifacts=stream_agent_id,
                output_delivery=output_delivery,
                public_base_url=stream_base_url,
            )
            store_task(state, running_task)
            _record_stream_debug("build_agent_start", stream_debug_id=stream_debug_id, task_id=task_id)
            agent = _build_agent_for_request(spec, metadata)
            agent_name = spec.get_name(agent)
            agent_version = spec.get_version(agent)
            _configure_agent_client_if_available(
                agent,
                agent_name=agent_name,
                credentials=credentials,
            )
            _record_stream_debug("build_agent_done", stream_debug_id=stream_debug_id, task_id=task_id)
            reason_event = _reason("agent_start")
            _record_stream_debug(
                "yield_before",
                stream_debug_id=stream_debug_id,
                stream_event=reason_event.get("event"),
                message=reason_event.get("message"),
                line_bytes=len((json.dumps(reason_event) + "\n").encode("utf-8")),
            )
            yield json.dumps(reason_event) + "\n"
            _record_stream_debug(
                "yield_after",
                stream_debug_id=stream_debug_id,
                stream_event=reason_event.get("event"),
                message=reason_event.get("message"),
            )
            time.sleep(0.1)
            _record_stream_debug("agent_run_start", stream_debug_id=stream_debug_id, task_id=task_id)
            import queue
            import threading

            progress_queue: queue.Queue = queue.Queue()
            sentinel = object()
            worker_state: Dict[str, Any] = {}

            def _live_progress_callback(event: Dict[str, Any]) -> None:
                message = event.get("message") if isinstance(event, dict) else None
                stage = event.get("stage") if isinstance(event, dict) else None
                _record_stream_debug(
                    "agent_progress_callback",
                    stream_debug_id=stream_debug_id,
                    agent_id=spec.agent_id,
                    stage=stage,
                    message=message,
                )
                progress_queue.put(
                    _make_event(
                        "progress",
                        message=message or f"The {spec.agent_id} reported a workflow update.",
                        stage=stage,
                        payload=event,
                    )
                )

            def _run_agent_worker() -> None:
                try:
                    worker_state["result"] = _call_agent_with_optional_progress(
                        spec,
                        agent,
                        query,
                        dataset_paths,
                        progress_callback=_live_progress_callback,
                        parameters=metadata,
                    )
                except Exception as worker_exc:
                    worker_state["error"] = worker_exc
                finally:
                    progress_queue.put(sentinel)

            threading.Thread(target=_run_agent_worker, daemon=True).start()
            last_heartbeat = time.time()
            while True:
                try:
                    progress_event = progress_queue.get(timeout=10)
                except queue.Empty:
                    if _task_status(state, task_id) == "canceled":
                        raise RuntimeError("Task was canceled.")
                    elapsed = int(time.time() - last_heartbeat)
                    heartbeat = _make_event(
                        "progress",
                        message=(
                            "I'm still working. Long LLM calls, code execution, "
                            "or geospatial file processing can take a little while."
                        ),
                        stage="heartbeat",
                        payload={"elapsed_seconds_since_last_update": elapsed},
                    )
                    yield json.dumps(heartbeat) + "\n"
                    last_heartbeat = time.time()
                    continue
                if progress_event is sentinel:
                    break
                if _task_status(state, task_id) == "canceled":
                    raise RuntimeError("Task was canceled.")
                last_heartbeat = time.time()
                line = json.dumps(progress_event) + "\n"
                _record_stream_debug(
                    "yield_before",
                    stream_debug_id=stream_debug_id,
                    stream_event=progress_event.get("event"),
                    message=progress_event.get("message"),
                    stage=progress_event.get("stage"),
                    line_bytes=len(line.encode("utf-8")),
                )
                yield line
                _record_stream_debug(
                    "yield_after",
                    stream_debug_id=stream_debug_id,
                    stream_event=progress_event.get("event"),
                    message=progress_event.get("message"),
                    stage=progress_event.get("stage"),
                )
            if "error" in worker_state:
                raise worker_state["error"]
            result = worker_state.get("result")
            _record_stream_debug(
                "agent_run_done",
                stream_debug_id=stream_debug_id,
                task_id=task_id,
                progress_event_count=len(progress_events),
            )
            reason_event = _reason("agent_done")
            _record_stream_debug(
                "yield_before",
                stream_debug_id=stream_debug_id,
                stream_event=reason_event.get("event"),
                message=reason_event.get("message"),
                line_bytes=len((json.dumps(reason_event) + "\n").encode("utf-8")),
            )
            yield json.dumps(reason_event) + "\n"
            _record_stream_debug(
                "yield_after",
                stream_debug_id=stream_debug_id,
                stream_event=reason_event.get("event"),
                message=reason_event.get("message"),
            )
            time.sleep(0.1)
            _record_stream_debug("build_task_payload_start", stream_debug_id=stream_debug_id, task_id=task_id)
            task = _build_task_payload(
                task_id=task_id,
                agent_id=spec.agent_id,
                agent_name=agent_name,
                agent_version=agent_version,
                state="TASK_STATE_COMPLETED",
                query=query,
                requested_skill=requested_skill,
                result=result,
                error_message=None,
                agent_id_for_artifacts=stream_agent_id,
                output_delivery=output_delivery,
                public_base_url=stream_base_url,
            )
            stored_task = store_task(state, task)
            _record_stream_debug("build_task_payload_done", stream_debug_id=stream_debug_id, task_id=task_id)
            yield from _yield_event(
                "task_succeeded",
                status="successful",
                task_id=task_id,
                message="Task finished.",
                payload={"task_id": task_id},
            )
            yield from _yield_event("task_result", status_code=HTTPStatus.OK, task_id=task_id, payload=stored_task)
        except Exception as exc:
            _record_stream_debug(
                "agent_exception",
                stream_debug_id=stream_debug_id,
                task_id=locals().get("task_id"),
                error=str(exc),
            )
            reason_event = _reason("failed")
            _record_stream_debug(
                "yield_before",
                stream_debug_id=stream_debug_id,
                stream_event=reason_event.get("event"),
                message=reason_event.get("message"),
                line_bytes=len((json.dumps(reason_event) + "\n").encode("utf-8")),
            )
            yield json.dumps(reason_event) + "\n"
            _record_stream_debug(
                "yield_after",
                stream_debug_id=stream_debug_id,
                stream_event=reason_event.get("event"),
                message=reason_event.get("message"),
            )
            time.sleep(0.1)
            task = _build_task_payload(
                task_id=task_id,
                agent_id=spec.agent_id,
                agent_name=None,
                agent_version=None,
                state="TASK_STATE_FAILED",
                query=query,
                requested_skill=requested_skill,
                result=None,
                error_message=str(exc),
                agent_id_for_artifacts=stream_agent_id,
                output_delivery=output_delivery,
                public_base_url=stream_base_url,
            )
            stored_task = store_task(state, task)
            _record_stream_debug("failed_task_payload_done", stream_debug_id=stream_debug_id, task_id=task_id)
            yield from _yield_event(
                "task_failed",
                status="failed",
                task_id=task_id,
                message="Task failed.",
                payload={"task_id": task_id},
            )
            yield from _yield_event("task_result", status_code=HTTPStatus.INTERNAL_SERVER_ERROR, task_id=task_id, payload=stored_task)

    headers = {
        "X-Accel-Buffering": "no",
        "Cache-Control": "no-cache",
        "Connection": "keep-alive",
    }
    return Response(
        _event_stream(),
        mimetype="application/json",
        headers=headers,
    )


def load_describe_agent_json(spec: AgentSpec, base_url: str | None = None) -> Dict[str, Any] | None:
    file_path = JSON_DIR / f"{spec.agent_id}.json"
    if not file_path.exists():
        return None
    with file_path.open("r", encoding="utf-8") as file:
        payload = json.load(file)

    public_base_url = _public_base_url(base_url)
    profile = payload.get("profile")
    if isinstance(profile, dict):
        profile["base_url"] = f"{public_base_url}/agents/{spec.agent_id}"
    return payload


def handle_describe_agent(spec: AgentSpec) -> Response:
    service = request.args.get("SERVICE", "").upper()
    gas_request = request.args.get("REQUEST", "")
    if service != "GAS" or gas_request != "DescribeAgent":
        return _gas_error(
            "INVALID_ARGUMENT",
            "This endpoint supports SERVICE=GAS&REQUEST=DescribeAgent.",
            status_code=HTTPStatus.BAD_REQUEST,
        )

    payload = load_describe_agent_json(spec)
    if payload is None:
        return _gas_error(
            "NOT_FOUND",
            f"{spec.agent_id}.json was not found.",
            status_code=HTTPStatus.NOT_FOUND,
        )
    return _json_response(payload, HTTPStatus.OK)


def handle_agent_card(card: Dict[str, Any]) -> Response:
    return _json_response(card, HTTPStatus.OK)


def _get_stored_task(state: Dict[str, Any], task_id: str) -> Dict[str, Any] | None:
    lock = state.get("LOCK")
    if lock is None:
        return state["TASKS"].get(task_id)
    with lock:
        return state["TASKS"].get(task_id)


def handle_execute_task(spec: AgentSpec, state: Dict[str, Any]) -> Response:
    payload = _request_payload()
    if not isinstance(payload, dict):
        return _gas_error(
            "INVALID_ARGUMENT",
            "Request body must be a JSON object.",
            status_code=HTTPStatus.BAD_REQUEST,
        )
    try:
        mode = _extract_task_mode(payload)
        run_payload = _gas_execute_task_to_run_payload(payload)
    except ValueError as exc:
        return _gas_error(
            "INVALID_ARGUMENT",
            str(exc),
            status_code=HTTPStatus.BAD_REQUEST,
        )

    if mode == "stream":
        return stream_agent_from_payload(spec, state, run_payload, "1.0.0")
    if mode == "async":
        return submit_agent_task_from_payload(spec, state, run_payload, "1.0.0")
    return run_agent_from_payload(spec, state, run_payload, "1.0.0")


def handle_get_task_status(spec: AgentSpec, state: Dict[str, Any], task_id: str) -> Response:
    task = _get_stored_task(state, task_id)
    if task is None:
        return _gas_error(
            "TASK_NOT_FOUND",
            f"Task '{task_id}' was not found.",
            status_code=HTTPStatus.NOT_FOUND,
        )
    return _json_response({"task": task.get("task", {})}, HTTPStatus.OK)


def handle_get_task_result(spec: AgentSpec, state: Dict[str, Any], task_id: str) -> Response:
    task = _get_stored_task(state, task_id)
    if task is None:
        return _gas_error(
            "TASK_NOT_FOUND",
            f"Task '{task_id}' was not found.",
            status_code=HTTPStatus.NOT_FOUND,
        )
    task_status = task.get("task", {}).get("status")
    if task_status not in TERMINAL_STATUSES:
        return _json_response(
            {
                "task": task.get("task", {}),
                "message": "Task is not complete yet. Poll GetTaskStatus or try GetTaskResult later.",
            },
            HTTPStatus.ACCEPTED,
        )
    return _json_response(task, HTTPStatus.OK)


def handle_cancel_task(spec: AgentSpec, state: Dict[str, Any], task_id: str) -> Response:
    lock = state.get("LOCK")
    task = _get_stored_task(state, task_id)
    if task is None:
        return _gas_error(
            "TASK_NOT_FOUND",
            f"Task '{task_id}' was not found.",
            status_code=HTTPStatus.NOT_FOUND,
        )
    task_status = task.get("task", {}).get("status")
    if task_status in TERMINAL_STATUSES:
        return _gas_error(
            "TASK_CLOSED",
            f"Task '{task_id}' is already closed and cannot be canceled.",
            status_code=HTTPStatus.CONFLICT,
        )
    if lock is None:
        task["task"]["status"] = "canceled"
        task["task"]["terminal"] = True
        task["execution"]["status"] = "canceled"
        task["response"]["completed_at"] = _iso_now()
        state["CLOSED_TASKS"].add(task_id)
    else:
        with lock:
            task["task"]["status"] = "canceled"
            task["task"]["terminal"] = True
            task["execution"]["status"] = "canceled"
            task["response"]["completed_at"] = _iso_now()
            state["CLOSED_TASKS"].add(task_id)
    return _json_response(task, HTTPStatus.OK)


def handle_get_data_file(spec: AgentSpec, filename: str) -> Response:
    directory = _agent_data_dir(_public_agent_id(spec))
    return send_from_directory(directory, filename, as_attachment=True)


def handle_stream_debug_events() -> Response:
    limit_raw = request.args.get("limit", "200")
    try:
        limit = max(1, min(int(limit_raw), STREAM_DEBUG_MAX_EVENTS))
    except ValueError:
        limit = 200
    stream_debug_id = request.args.get("stream_debug_id")
    events = STREAM_DEBUG_LOGS
    if stream_debug_id:
        events = [event for event in events if event.get("stream_debug_id") == stream_debug_id]
    return _json_response(
        {
            "count": len(events[-limit:]),
            "events": events[-limit:],
        },
        HTTPStatus.OK,
    )


def handle_agent_status(spec: AgentSpec) -> Response:
    public_agent_id = _public_agent_id(spec)
    return _json_response(
        {
            "status": "available",
            "agent_id": spec.agent_id,
            "service_base": f"/agents/{spec.agent_id}",
            "data_directory": str(_agent_data_dir(public_agent_id)),
        },
        HTTPStatus.OK,
    )


def create_service_app(spec: AgentSpec) -> Flask:
    app = Flask(f"{spec.agent_id}_service")
    state = init_service_state()
    card = build_agent_card(spec)
    app.config["AGENT_SPEC"] = spec
    app.config["STATE"] = state
    app.config["CARD"] = card
    app.config["TASKS"] = state["TASKS"]
    app.config["CLOSED_TASKS"] = state["CLOSED_TASKS"]
    app.config["STREAM_AGENT_FROM_PAYLOAD"] = lambda payload, version=None: stream_agent_from_payload(spec, state, payload, version or "1.0.0")

    @app.route("/", methods=["GET"])
    def describe_agent() -> Response:
        return handle_describe_agent(spec)

    @app.route("/status", methods=["GET"])
    def agent_status() -> Response:
        return handle_agent_status(spec)

    @app.route("/tasks", methods=["POST"])
    def execute_task() -> Response:
        return handle_execute_task(spec, state)

    @app.route("/tasks/<task_id>/status", methods=["GET"])
    def get_task_status(task_id: str) -> Response:
        return handle_get_task_status(spec, state, task_id)

    @app.route("/tasks/<task_id>/result", methods=["GET"])
    def get_task_result(task_id: str) -> Response:
        return handle_get_task_result(spec, state, task_id)

    @app.route("/tasks/<task_id>/cancel", methods=["POST"])
    def cancel_task(task_id: str) -> Response:
        return handle_cancel_task(spec, state, task_id)

    @app.route("/data/<path:filename>", methods=["GET"])
    def get_data_file(filename: str) -> Response:
        return handle_get_data_file(spec, filename)

    if ENABLE_STREAM_DEBUG:
        @app.route("/debug/stream-events", methods=["GET"])
        def stream_debug_events() -> Response:
            return handle_stream_debug_events()

    return app




